org: pepperr
app: sls-typescript-http-api
service: sls-typescript-http-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    LINKS_TABLE: ${self:service}-urls-${sls:stage}
    USERS_TABLE: ${self:service}-users-${sls:stage}
    ACCOUNT_ID: ${env:ACCOUNT_ID}
    REGION: ${env:REGION}
    QUEUE_NAME: ${env:QUEUE_NAME}
    SCHEDULED_DEACTIVATE: ${env:SCHEDULED_DEACTIVATE}
    EMAIL: ${env:EMAIL}
    JWT_ACCESS_SECRET: ${env:JWT_ACCESS_SECRET}
    JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-plugin-scripts
  - serverless-auto-swagger

custom:
  scripts:
    hooks:
      'deploy:finalize': node verifyEmail.mjs
  esbuild:
    bundle: true
    minify: false
    target: 'node18'
    platform: 'node'
    concurrency: 10
  autoswagger:
    title: 'Severless Academy ShortLinker Project'
    host: 'localhost:3000/dev/'
    typefiles: [ './schemas/modelsSchema.d.ts' ]
    apiKeyHeaders: [ 'Authorization' ]
  dotenv:
    include:
      - .env

functions:
  checkIsAuth:
    handler: functions/checkIsAuth.checkIsAuth
  signUp:
    handler: functions/signUp.signUp
    events:
      - http:
          path: /sign-up
          method: post
          cors: true
          bodyType: User
          request:
            schemas:
              application/json: ${file(schemas/signUpSchema.json)}
          responseData:
            200:
              bodyType: SignUpResponse
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:PutItem'
          - 'dynamodb:GetItem'
        Resource:
          - !GetAtt UsersTable.Arn
          - !GetAtt UrlsTable.Arn
  signIn:
    handler: functions/signIn.signIn
    events:
      - http:
          path: /sign-in
          method: post
          cors: true
          bodyType: User
          request:
            schemas:
              application/json: ${file(schemas/signInSchema.json)}
          responseData:
            200:
              bodyType: SignInResponse
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:PutItem'
          - 'dynamodb:GetItem'
        Resource:
          - !GetAtt UsersTable.Arn
          - !GetAtt UrlsTable.Arn
  profile:
    handler: functions/getMyProfile.getMyProfile
    events:
      - http:
          path: /profile
          method: get
          cors: true
          bodyType: User
          responseData:
            200:
              bodyType: ProfileResponse
          authorizer:
            name: checkIsAuth
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 3600
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:*'
        Resource:
          - !GetAtt UsersTable.Arn
          - !GetAtt UrlsTable.Arn
  refreshTokens:
    handler: functions/refreshTokens.refreshTokens
    events:
      - http:
          path: /refresh
          method: get
          cors: true
          responseData:
            200:
              bodyType: TokenResponse
          authorizer:
            name: checkIsAuth
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 3600
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:*'
        Resource:
          - !GetAtt UsersTable.Arn
  scheduledDeactivateUrl:
    handler: functions/scheduledDeactivateUrl.scheduledDeactivateUrl
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - 'deactivator'
            detail-type:
              - 'scheduled-deactivator'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:DeleteItem'
          - 'sqs:SendMessage'
          - 'ses:*'
          - 'events:*'
          - 'scheduler:*'
        Resource: '*'
  sendEmailNotification:
    handler: functions/sendEmailNotification.sendEmailNotification
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ShortUrlQueue
              - Arn
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:*'
          - 'sqs:*'
          - 'ses:*'
        Resource: '*'
  shortUrl:
    handler: functions/shortUrl.shortUrlWithMiddleware
    middy:
      use:
        - name: httpJsonBodyParser
        - name: validateUrlMiddleware
    events:
      - http:
          path: /
          method: post
          cors: true
          bodyType: Url
          request:
            schemas:
              application/json: ${file(schemas/urlSchema.json)}
          responseData:
            200:
              bodyType: UrlResponse
          authorizer:
            name: checkIsAuth
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 3600
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:PutItem'
          - 'dynamodb:Scan'
          - 'dynamodb:Query'
          - 'dynamodb:GetItem'
          - 'sqs:SendMessage'
          - 'events:PutEvents'
          - 'scheduler:CreateSchedule'
          - 'lambda:InvokeFunction'
        Resource: '*'
  redirectToUrl:
    handler: functions/redirectToUrl.redirectToUrl
    events:
      - http:
          path: /{shortedUrl}
          method: get
          cors: true
          responseData:
            302:
              bodyType: ''
          response:
            headers:
              Location:
                type: 'STRING'
            statusCodes:
              302:
                pattern: ''
                headers:
                  Location: 'integration.response.headers.Location'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:Scan'
          - 'dynamodb:GetItem'
          - 'dynamodb:DeleteItem'
          - 'sqs:SendMessage'
          - 'ses:*'
        Resource:
          - !GetAtt UrlsTable.Arn
          - !GetAtt ShortUrlQueue.Arn
  deactivateUrl:
    handler: functions/deactivateUrl.deactivateUrl
    events:
      - http:
          path: /deactivateURL
          method: delete
          cors: true
          bodyType: Deactivate
          request:
            schemas:
              application/json: ${file(schemas/deactivateSchema.json)}
          responseData:
            200:
              bodyType: DeactivateUrlResponse
          authorizer:
            name: checkIsAuth
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 3600
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:Scan'
          - 'dynamodb:DeleteItem'
          - 'sqs:SendMessage'
          - 'ses:*'
        Resource:
          - !GetAtt UrlsTable.Arn
          - !GetAtt ShortUrlQueue.Arn

resources:
  Resources:
    EventBridgerRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: event-bridger-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - events.amazonaws.com
                  - scheduler.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: LambdaInvokeAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: '*'
    ShortUrlEvent:
      Type: AWS::Events::Rule
      Properties:
        EventPattern:
          source:
            - 'deactivator'
          detail-type:
            - 'scheduled-deactivator'
        Targets:
          - Arn: arn:aws:lambda:${self:provider.environment.REGION}:${self:provider.environment.ACCOUNT_ID}:function:${self:provider.environment.SCHEDULED_DEACTIVATE}
            Id: 'DeactivateTarget'
    ShortUrlQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.QUEUE_NAME}

    UrlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-urls-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-users-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5


