// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Severless Academy ShortLinker Project",
    "version": "1"
  },
  "paths": {
    "/sign-up": {
      "post": {
        "summary": "signUp",
        "description": "",
        "operationId": "signUp.post./sign-up",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/SignUpResponse"
            }
          }
        }
      }
    },
    "/sign-in": {
      "post": {
        "summary": "signIn",
        "description": "",
        "operationId": "signIn.post./sign-in",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/SignInResponse"
            }
          }
        }
      }
    },
    "/profile": {
      "get": {
        "summary": "profile",
        "description": "",
        "operationId": "profile.get./profile",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/ProfileResponse"
            }
          }
        }
      }
    },
    "/refresh": {
      "get": {
        "summary": "refreshTokens",
        "description": "",
        "operationId": "refreshTokens.get./refresh",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/TokenResponse"
            }
          }
        }
      }
    },
    "/": {
      "post": {
        "summary": "shortUrl",
        "description": "",
        "operationId": "shortUrl.post./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Url"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/UrlResponse"
            }
          }
        }
      }
    },
    "/{shortedUrl}": {
      "get": {
        "summary": "redirectToUrl",
        "description": "",
        "operationId": "redirectToUrl.get./{shortedUrl}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "shortedUrl",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "302": {
            "description": "302 response"
          }
        }
      }
    },
    "/deactivateURL": {
      "delete": {
        "summary": "deactivateUrl",
        "description": "",
        "operationId": "deactivateUrl.delete./deactivateURL",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Deactivate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/DeactivateUrlResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "User": {
      "properties": {
        "email": {
          "title": "User.email",
          "type": "string"
        },
        "password": {
          "title": "User.password",
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ],
      "additionalProperties": false,
      "title": "User",
      "type": "object"
    },
    "Url": {
      "properties": {
        "originalUrl": {
          "title": "Url.originalUrl",
          "type": "string"
        },
        "disposable": {
          "title": "Url.disposable",
          "type": "boolean"
        },
        "expiresAt": {
          "title": "Url.expiresAt",
          "type": "number"
        }
      },
      "required": [
        "originalUrl",
        "disposable",
        "expiresAt"
      ],
      "additionalProperties": false,
      "title": "Url",
      "type": "object"
    },
    "Deactivate": {
      "properties": {
        "linkToDeactivate": {
          "title": "Deactivate.linkToDeactivate",
          "type": "string"
        }
      },
      "required": [
        "linkToDeactivate"
      ],
      "additionalProperties": false,
      "title": "Deactivate",
      "type": "object"
    },
    "SignUpResponse": {
      "properties": {
        "id": {
          "title": "SignUpResponse.id",
          "type": "string"
        },
        "accessToken": {
          "title": "SignUpResponse.accessToken",
          "type": "string"
        },
        "refreshToken": {
          "title": "SignUpResponse.refreshToken",
          "type": "string"
        }
      },
      "required": [
        "id",
        "accessToken",
        "refreshToken"
      ],
      "additionalProperties": false,
      "title": "SignUpResponse",
      "type": "object"
    },
    "SignInResponse": {
      "properties": {
        "id": {
          "title": "SignInResponse.id",
          "type": "string"
        },
        "accessToken": {
          "title": "SignInResponse.accessToken",
          "type": "string"
        },
        "refreshToken": {
          "title": "SignInResponse.refreshToken",
          "type": "string"
        }
      },
      "required": [
        "id",
        "accessToken",
        "refreshToken"
      ],
      "additionalProperties": false,
      "title": "SignInResponse",
      "type": "object"
    },
    "ProfileResponse": {
      "properties": {
        "userId": {
          "title": "ProfileResponse.userId",
          "type": "string"
        },
        "userEmail": {
          "title": "ProfileResponse.userEmail",
          "type": "string"
        },
        "userUrls": {
          "items": [],
          "additionalItems": false,
          "minItems": 0,
          "title": "ProfileResponse.userUrls",
          "type": "array"
        }
      },
      "required": [
        "userId",
        "userEmail",
        "userUrls"
      ],
      "additionalProperties": false,
      "title": "ProfileResponse",
      "type": "object"
    },
    "TokenResponse": {
      "properties": {
        "id": {
          "title": "TokenResponse.id",
          "type": "string"
        },
        "accessToken": {
          "title": "TokenResponse.accessToken",
          "type": "string"
        },
        "refreshToken": {
          "title": "TokenResponse.refreshToken",
          "type": "string"
        }
      },
      "required": [
        "id",
        "accessToken",
        "refreshToken"
      ],
      "additionalProperties": false,
      "title": "TokenResponse",
      "type": "object"
    },
    "UrlResponse": {
      "properties": {
        "fullUrl": {
          "title": "UrlResponse.fullUrl",
          "type": "string"
        },
        "urlId": {
          "title": "UrlResponse.urlId",
          "type": "string"
        }
      },
      "required": [
        "fullUrl",
        "urlId"
      ],
      "additionalProperties": false,
      "title": "UrlResponse",
      "type": "object"
    },
    "DeactivateUrlResponse": {
      "properties": {
        "id": {
          "title": "DeactivateUrlResponse.id",
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false,
      "title": "DeactivateUrlResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "host": "localhost:3000/dev/"
};